### ISSUE TITLE
Is this project still maintained / working?

### ISSUE THREAD

**Issue by dara-rockwell** [Open-SL/serverless-permission-generator#24]
It's been over a year since any contributions were made, so just taking the project's pulse.

**Comment by nadunindunil** [comment]
The project will always be a work in progress.
As a maintainer, I have done the best I could with searching and adding the least privileged permissions into the project.  
However, This should be a crowdsources project because one maintainer cannot implement all the permutations of serverless project deployments.
I am more than happy to hear new ideas or feedback to improve the project.
